apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-efmq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-efmq
    app.kubernetes.io/part-of: test-app-819
  name: maven-hello-world-efmq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-efmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-efmq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-819/maven-hello-world-efmq@sha256:2db88062d25aba9d7f07d33d3e4d72a59e64ab13d50a562e9a8092be31f250cb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
